version: '3'

services:
  composer:
    image: composer:1.8
    volumes:
      - .:/app
    environment:
      -  AWS_ACCESS_KEY_ID=your_aws_access_key_id
      -  AWS_SECRET_ACCESS_KEY=your_secret_access_key
